### PR TITLE
Landing Page Styles fixed + refactored

### PR DESCRIPTION
**Pull request by MatteuSan**

### CODE REVIEW

**Comment by MatteuSan** [comment]
Can't do commands page yet, because am sleepy lmao

**Comment by AykutSarac** [comment]
There seem to be some issues while importing styles
`Module build failed (from ./node_modules/sass-loader/dist/cjs.js): SassError: Can't find stylesheet to import. ╷ 11 │ @use '~@growstocks/stack/Core/Theme'; │ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ╵ layouts\default.vue 11:1 root`

**Comment by AykutSarac** [comment]
Images are not responsive and button links broken `http://localhost:3000/[object%20Object]`

**Comment by MatteuSan** [comment]
> There seem to be some issues while importing styles
> `Module build failed (from ./node_modules/sass-loader/dist/cjs.js): SassError: Can't find stylesheet to import. ╷ 11 │ @use '~@growstocks/stack/Core/Theme'; │ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ╵ layouts\default.vue 11:1 root`

do `npm install` for this to be fixed

**Comment by MatteuSan** [comment]
> Images are not responsive and button links broken `http://localhost:3000/[object%20Object]`

this one i'll go and fix it

**Comment by AykutSarac** [comment]
Button component giving following error:
```js
[Vue warn]: Error in data(): "ReferenceError: logo is not defined"                                                                                         11:50:33  

found in

---> <Button> at components/Button.vue
       <Navbar> at components/Navbar.vue
         <Layouts/default.vue> at layouts/default.vue
           <Root>
```

**Comment by MatteuSan** [comment]
Done

**Comment by MatteuSan** [comment]
the done

**Comment by AykutSarac** [comment]
Link to section doesn't work
image

**Comment by MatteuSan** [comment]
done

**Comment by AykutSarac** [comment]
Thank you for your contribution @MatteuSan! It has been merged to master and will be taken to prouction after little touches.

**Pull request merged**
